---
---
title: "Comparison of Air pollution exposure models - RAQDPS-FW and CanOSSEM"
output: html_document
editor: 
  markdown: 
    wrap: 72
---

```{r setup, message = FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(lubridate)
library(stringr)
library(scales)
library(ggthemes)
library(heemod)
library(bcmaps)
require(sf)
```

```{r}
projection <- read.csv("./data/gemmach_2019_2036.csv")
raqdps <- read.csv("./data/raqdps_mo_hsda_2012_2023.csv")
raqdpsfw <- read.csv("./data/raqdpsfw_mo_hsda_2012_2023.csv")
```

# Functions for later
```{r}
haLineMo <- function (data, title) {
    ggplot(data) +
    geom_line(aes(x = date, y = background_pm25, colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(date_labels = "%m-%Y", date_breaks = "12 month") +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none"
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    x = "",
    y = "µg/m³")
}


haLineMo2 <- function (data, title) {
    ggplot(data) +
    geom_line(aes(x = date, y = wildfire_pm25, colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(date_labels = "%m-%Y", date_breaks = "12 month") +
    theme_few(base_size = 8) +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none"
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    x = "",
    y = "µg/m³")
}



haLineMo_project <- function (data, title, sub) {
    ggplot(data) +
    geom_line(aes(x = date, y = !!enquo(sub), colour = HLTH_SERVICE_DLVR_AREA_NAME), linewidth = 0.5) +
    scale_x_date(breaks = seq(as.Date("2020-01-01"), as.Date("2100-01-01"), by = "5 years"),
                 date_minor_breaks = "1 year",
                 date_labels = "%Y") +
    theme_few(base_size = 8) +
    theme(
     axis.text.x = element_text(angle = 90, hjust = 1),
      legend.position = "none",
      panel.grid.minor = element_blank(),      # Remove minor grid lines
      panel.grid.major = element_blank(), # Keep major grid lines if desired
      axis.ticks = element_line(color = "black"), # Enable ticks
      axis.ticks.length = unit(0.15, "cm")     # Adjust tick length if needed
    ) +
    facet_wrap(~ HLTH_SERVICE_DLVR_AREA_NAME) +
    labs(title = title,
    ylim(0, 100),
    x = "",
    y = "µg/m³")
}
```
# Some cleaning and prep
```{r}
combined_raq <- raqdps %>%
  select(c("average_mo", "date", "HLTH_SERVICE_DLVR_AREA_NAME")) %>%
  inner_join(raqdpsfw, by = c("date", "HLTH_SERVICE_DLVR_AREA_NAME"), suffix = c("_raqdps", "_raqdpsfw"))

wildfire_smoke <- combined_raq %>%
  mutate(sanity = average_mo_raqdpsfw >= average_mo_raqdps,
         wildfire_pm25 = average_mo_raqdpsfw - average_mo_raqdps) 

summary(wildfire_smoke$wildfire_pm25)  
wildfire_smoke %>% glimpse()
summary(wildfire_smoke$sanity) 


# Cancelling the negative wildfire contributions
wildfire_smoke <- wildfire_smoke %>% 
  select(HLTH_SERVICE_DLVR_AREA_NAME, date, wildfire_pm25, average_mo_raqdpsfw, average_mo_raqdps) %>%
  mutate(wildfire_pm25 = if_else(wildfire_pm25<0, 0, wildfire_pm25)) %>%
  mutate(wildfire_pm25 =replace_na(wildfire_pm25, 0)) %>%
  mutate(date = ymd(date)) %>%
  arrange(HLTH_SERVICE_DLVR_AREA_NAME, date)

summary(wildfire_smoke$wildfire_pm25)  
wildfire_smoke %>% glimpse()
summary(wildfire_smoke$sanity) 

haLineMo2(wildfire_smoke, "Wildfire contribution to total PM2.5, derived from RAQDPS-FW (total PM2.5 with wildfire smoke) - RAQDPS (total PM2.5 without wildfire smoke)")

saveRDS(wildfire_smoke, "average_monthly_wildfire_smoke_HSDA_2018_2023.rds")

## Averaging wildfire smoke to 5-year, monthly.

wildfire_smoke_avg <- wildfire_smoke %>%
  mutate(year = year(date), month = month(date), day = 1) %>%
  group_by(HLTH_SERVICE_DLVR_AREA_NAME, month) %>%
  summarize(
    wildfire_pm25 = mean(wildfire_pm25, na.rm = TRUE),
    average_mo_raqdpsfw = mean(average_mo_raqdpsfw, na.rm = TRUE),
    average_mo_raqdps = mean(average_mo_raqdps, na.rm = TRUE),
    date = as.Date(paste(year[1], month, day, sep = "-")),
    .groups = "drop"
  )

glimpse(wildfire_smoke_avg)

saveRDS(wildfire_smoke_avg, "average_5yr_monthly_wildfire_smoke_HSDA_2018_2023.rds")

```

# GEM-MACH to HSDA
```{r}
cds <- st_read("./data/shape/lcd_000a21a_e.shp")
bc_hsda <- health_hsda()

st_crs(cds)
st_crs(bc_hsda)

# converts cds to HSDA coordinate reference system
cds_transformed <- st_transform(cds, crs = 3005)

# merges CDUID and HSDA together based on coordinate reference system
cd_hsda_mapping <- st_join(bc_hsda, cds_transformed, join = st_intersects)

glimpse(cd_hsda_mapping)

projection1_hsda <- projection %>%
  mutate(CDUID = as.character(CDUID)) %>%
  left_join(cd_hsda_mapping, by = "CDUID") %>%
  select(HLTH_SERVICE_DLVR_AREA_NAME, month, year, date, background_pm25) %>%
#  filter(!is.na(HLTH_SERVICE_DLVR_AREA_NAME)) %>%
  mutate(date = ymd(date))

glimpse(projection1_hsda)


cds <- st_read("./data/shape/lcd_000a21a_e.shp")
bc_hsda <- health_hsda()

st_crs(cds)
st_crs(bc_hsda)

# converts cds to HSDA coordinate reference system
cds_transformed <- st_transform(cds, crs = 3005)

# merges CDUID and HSDA together based on coordinate reference system
cd_hsda_mapping <- st_join(bc_hsda, cds_transformed, join = st_intersects)

glimpse(projection)


projection_hsda <- projection %>%
  mutate(CDUID = as.character(CDUID)) %>%
  left_join(cd_hsda_mapping, by = "CDUID") %>%
  select(HLTH_SERVICE_DLVR_AREA_NAME, month, year, date, background_pm25) %>%
  filter(!is.na(HLTH_SERVICE_DLVR_AREA_NAME)) %>%
  mutate(date = ymd(date))

projection_hsda_cleaned <- projection_hsda %>%
  group_by(HLTH_SERVICE_DLVR_AREA_NAME, month, year, date) %>%
  summarise(background_pm25 = mean(background_pm25, na.rm = TRUE)) %>%
  ungroup()

duplicates_check <- projection_hsda %>%
  group_by(HLTH_SERVICE_DLVR_AREA_NAME, month, year) %>%
  tally() %>%
  filter(n > 1)
# View duplicate rows, if any
if (nrow(duplicates_check) > 0) {
  print("Duplicates found:")
  print(duplicates_check)
} else {
  print("Each HSDA has a unique background_pm25 for each month and year.")
}

duplicates_check <- projection_hsda_cleaned %>%
  group_by(HLTH_SERVICE_DLVR_AREA_NAME, month, year) %>%
  tally() %>%
  filter(n > 1)
# View duplicate rows, if any
if (nrow(duplicates_check) > 0) {
  print("Duplicates found:")
  print(duplicates_check)
} else {
  print("Each HSDA has a unique background_pm25 for each month and year.")
}

glimpse(projection_hsda_cleaned)

haLineMo_project(projection_hsda_cleaned, "GEM-MACH Monthly", background_pm25)

haLineMo_project(projection1_hsda, "GEM-MACH Monthly", background_pm25)


```
# Projection function
```{r}

#| column: page
#| out-width: 100%
#| 
#scaling factor per 10 years

project_future_pm25 <- function(scaling_type='linear', 
                                scaling_factor=1, 
                                reference_year=2100){
# calculate based on scaling type
  if (scaling_type=='linear'){
    message(paste0(
      "Assuming a linear annual increase in wildfire activity, ", 
      reference_year, 
      " assumed to be ",
      scaling_factor, " times as bad as 2023"))
 # applies scaling factor to projection data
    scaling_factor <- (scaling_factor-1)/(reference_year-2023)
    future_pm25 <- projection %>%
      filter(year > 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
      left_join(average_monthly_wildfire_smoke, 
              by=c('HLTH_SERVICE_DLVR_AREA_NAME'='HLTH_SERVICE_DLVR_AREA_NAME',
                   "month")) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 
      return(future_pm25)
  }

}


map_future_project <- function(scaling_factor, 
                               selected_year,
                               title, 
                               reference_year){
  p <- project_future_pm25(scaling_factor = scaling_factor, 
                           reference_year=reference_year) %>%
  filter(year %in% c(selected_year)) %>% 
  left_join(cds, by="CDUID") %>%
  st_as_sf() %>%
    ggplot() + 
    geom_sf(aes(fill=total_pm25), size=0.01, alpha=0.9) +
    ggtitle(paste0(title, " wildfire increase till ",  reference_year)) +
    scale_fill_viridis_c(option="inferno", limits = c(0, 60)) +
    theme(legend.position="bottom") +
    facet_wrap(~month) +
    theme_few()

  print(p)
}

# map_future_project(1, 2024, "2024 - 0%", reference_year=2036)
# map_future_project(1, 2030, "2030 - 0%", reference_year=2036)
# map_future_project(1, 2036, "2036 - 0%", reference_year=2036)


```

# Projection prep, using wildfire_smoke (2018-2023)
```{r}
# Inputs
# wildfire_smoke: difference between raqdpsfw (total PM2.5 with wildfire contribution) - raqdps (total PM2.5 WITHOUT wildfire contribution)
# projection_hsda: predicted baseline PM2.5 (analogous to base raqdps)

glimpse(wildfire_smoke)
glimpse(projection_hsda_cleaned)

filter_wildfire_smoke <- wildfire_smoke %>%
  filter(lubridate::year(date) <= 2023)%>%
  mutate(month = month(date))

filter_projection_hsda <- projection_hsda_cleaned %>%
  filter(lubridate::year(date) >= 2023) %>%
  mutate(month = month(date))

glimpse(filter_wildfire_smoke)
glimpse(filter_projection_hsda)

projection_historical_hsda <- filter_projection_hsda %>%
  left_join(filter_wildfire_smoke %>% select(-date), 
            by = c("HLTH_SERVICE_DLVR_AREA_NAME" = "HLTH_SERVICE_DLVR_AREA_NAME", 
                   "month" = "month"))

glimpse(projection_historical_hsda)

projection_1 <- project_future_pm25(projection_historical_hsda)

# 25% scaling factor, 2100 reference year
scaling_factor_0 <- (1-1)/(2100-2023)
scaling_factor_25 <- (1.25-1)/(2100-2023)
scaling_factor_50 <- (1.50-1)/(2100-2023)

future_pm25_0 <- projection_historical_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_0),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 

future_pm25_25 <- projection_historical_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_25),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 

future_pm25_50 <- projection_historical_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_50),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 



glimpse(future_pm25_0)
glimpse(future_pm25_25)
glimpse(future_pm25_50)


line_pm25_0 <- haLineMo_project(future_pm25_0, "Projected Total PM2.5, 0% increase from 2023-2100", total_pm25)

line_pm25_25 <- haLineMo_project(future_pm25_25, "Projected Total PM2.5, 25% increase from 2023-2100", total_pm25)

line_pm25_50 <- haLineMo_project(future_pm25_50, "Projected Total PM2.5, 50% increase from 2023-2100", total_pm25)

ggsave("line_pm25_0.png", plot = line_pm25_0, width = 9, height = 5)
ggsave("line_pm25_25.png", plot = line_pm25_25, width = 9, height = 5)
ggsave("line_pm25_50.png", plot = line_pm25_50, width = 9, height = 5)

write.csv(future_pm25_0, "future_pm25_0_2023_2036.csv")
write.csv(future_pm25_25, "future_pm25_25_2023_2036.csv")
write.csv(future_pm25_50, "future_pm25_50_2023_2036.csv")
```

# Using 5-year average wildfire smoke exposure instead...
```{r}
wildfire_smoke_avg

glimpse(wildfire_smoke_avg)
glimpse(projection_hsda_cleaned)

filter_wildfire_smoke_5yr <- wildfire_smoke_avg %>%
  filter(lubridate::year(date) <= 2023) %>%
  mutate(month = month(date))

filter_projection_hsda <- projection_hsda_cleaned %>%
  filter(lubridate::year(date) >= 2023) %>%
  mutate(month = month(date))

glimpse(filter_wildfire_smoke_5yr)
glimpse(filter_projection_hsda)

projection_historical5yr_hsda <- filter_projection_hsda %>%
  left_join(filter_wildfire_smoke_5yr %>% select(-date), 
            by = c("HLTH_SERVICE_DLVR_AREA_NAME" = "HLTH_SERVICE_DLVR_AREA_NAME", 
                   "month" = "month"))

glimpse(projection_historical5yr_hsda)



# 25% scaling factor, 2100 reference year
scaling_factor_0 <- (1-1)/(2100-2023)
scaling_factor_25 <- (1.25-1)/(2100-2023)
scaling_factor_50 <- (1.50-1)/(2100-2023)

future_pm25_0 <- projection_historical5yr_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_0),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 

future_pm25_25 <- projection_historical5yr_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_25),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 

future_pm25_50 <- projection_historical5yr_hsda %>%
      filter(year >= 2023) %>%
      mutate(HLTH_SERVICE_DLVR_AREA_NAME = as.character(HLTH_SERVICE_DLVR_AREA_NAME),
           month = lubridate::month(date)) %>%
    mutate(
      factor =(1+(year-2023)*scaling_factor_50),
      wildfire_pm25_scaled = factor*wildfire_pm25,
      total_pm25 = background_pm25 + wildfire_pm25_scaled) 



glimpse(future_pm25_0)
glimpse(future_pm25_25)
glimpse(future_pm25_50)


line_pm25_0a <- haLineMo_project(future_pm25_0, "Projected Total PM2.5, RAQDPS (5-year average), 0% increase from 2023-2100", total_pm25)

line_pm25_25a <- haLineMo_project(future_pm25_25, "Projected Total PM2.5, RAQDPS (5-year average), 25% increase from 2023-2100", total_pm25)

line_pm25_50a <- haLineMo_project(future_pm25_50, "Projected Total PM2.5, RAQDPS (5-year average), 50% increase from 2023-2100", total_pm25)

ggsave("line_pm25_5yr_0.png", plot = line_pm25_0a, width = 9, height = 5)
ggsave("line_pm25_5yr_25.png", plot = line_pm25_25a, width = 9, height = 5)
ggsave("line_pm25_5yr_50.png", plot = line_pm25_50a, width = 9, height = 5)


saveRDS(future_pm25_0, "future_pm25_5yr_0_2023_2036.rds")
saveRDS(future_pm25_25, "future_pm25_5yr_25_2023_2036.rds")
saveRDS(future_pm25_50, "future_pm25_5yr_50_2023_2036.rds")
```
